name: Help me!
description: If you need help using the port.
labels: [help wanted]
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe your problem here."
    validations:
      required: true

  - type: dropdown
    id: modding
    attributes:
      label: "Are you modding a build from source or with Lua?"
      options:
        - Lua
        - Source
        - Lua and Source
        - I am not modding
    validations:
      required: true

  - type: dropdown
    id: btarget
    attributes:
      label: "What is your build target?"
      options:
        - "Desktop (Linux, Windows or Mac)"
        - "Android"
        - "iOS"
        - "HashLink"
        - "Flash/AIR"
        - "Other/Unknown/I don't know"
    validations:
      required: true

  - type: dropdown
    id: psychver
    attributes:
      label: "Which plus engine version you're on?"
      options:
        - "1.2"
        - "1.1"
        - "1.0.6"
        - "1.0.5"
        - "1.0"
        - "0.8.5 / older"
    validations:
      required: true

  - type: input
    id: buildsummary
    attributes:
      label: "Did you edit anything in this build? If so, mention or summarize your changes."
      placeholder: "Yes, I edited ClientPrefs.hx and tried to add a new setting"
    validations:
      required: false
